services:
  - type: web
    name: cameroun-aventure
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist/cameroun-aventure/browser
    envVars:
      - key: NODE_VERSION
        value: "20.11.0"
